### PR TITLE
Make Xwayland optional

### LINKED ISSUE #147: Make Xwayland optional

### PR DESCRIPTION
**Pull request by versusvoid**
Fix #147

- [x] runtime
- [x] compile time

### CODE REVIEW

**Comment by emersion** [comment]
I think the issue was about making xwayland an optional dependency at compile-time, not disabling it at runtime.

**Comment by SirCmpwn** [comment]
Yeah, but I don't mind making it optional both ways.

**Comment by SirCmpwn** [comment]
I think the API should stay the same but if compiled without xwayland support then wlr_xwayland_create should return NULL (and log the issue).

**Comment by versusvoid** [comment]
So whole xwayland directory will be compiled in library, but `_create`, `_destroy` and `_activate` won't work? What the point?

**Comment by SirCmpwn** [comment]
Eh, you're right.

**Pull request merged**
