### PR TITLE
Use posix_fallocate when available

### PR DESCRIPTION
**Pull request by emersion**
* `posix_fallocate` was never used
* ~~Use `memfd_create` and seals when possible~~

### CODE REVIEW

**Comment by emersion** [comment]
Wait, these checks are wrong:

```
Header <sys/memfd.h> has symbol "memfd_create": NO
Header <sys/memfd.h> has symbol "MFD_ALLOW_SEALING": NO
```

Hmm, what's wrong here?

**Comment by emersion** [comment]
>It might actually be defined in some dumb GNU-specific header that memfd.h pulls in

Ah, it's defined in `mman.h` only if `_GNU_SOURCE` is enabled. Two solutions:

1. Don't use `memfd_create` and seals
2. Redefine constants we need and use a syscall, see https://gitlab.gnome.org/GNOME/gtk/blob/master/gdk/wayland/gdkdisplay-wayland.c#L1207

**Comment by SirCmpwn** [comment]
I'm okay with either.

**Comment by emersion** [comment]
Let's just fix that `posix_fallocate` detection for now.

**Comment by emersion** [comment]
#1152 and #1153 can't be merged together, because this PR uses `#include <wlr/config.h>`. When one of those gets merged I'll fix the other one.

**Comment by emersion** [comment]
Updated

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
