### PR TITLE
Remove orbital screenshooter and gamma-control

### PR DESCRIPTION
**Pull request by emersion**
These are undocumented, outdated protocols that have a better wlr-protocols
equivalent.

Sway PR: https://github.com/swaywm/sway/pull/4204

### CODE REVIEW

**Comment by ddevault** [comment]
Thanks! \o\

**Comment by ammen99** [comment]
Just for the record, this is a breaking change.

**Comment by emersion** [comment]
Oh, right -- forgot to add the label. Thanks :)

**Comment by Shatur95** [comment]
@emersion, what should I use to take screenshots in Wayland environment?

**Comment by emersion** [comment]
The screencopy protocol from https://github.com/swaywm/wlr-protocols

**Comment by Shatur95** [comment]
@emersion, thank you!

**Pull request merged**
