### PR TITLE
backend/drm: take output state as arg in commit functions, take 2

### PR DESCRIPTION
**Pull request by emersion**
This is a re-do of #2704, but with the changes better split up and a few enhancements.

### CODE REVIEW

**Comment by kennylevinsen** [comment]
> Preliminary work for future commit(s)

How will I know if and when these future commits have arrived? :)

LGTM other than those two commits messages.

**Comment by kennylevinsen** [comment]
Maybe we should get this merged before more merge conflicts arise...

**Comment by emersion** [comment]
Thanks for having a look! Rebased, hopefully with better commit messages this time.

**Comment by emersion** [comment]
Note, the original motivation for this refactoring is https://github.com/swaywm/wlroots/pull/2829, which is itself required for https://github.com/swaywm/wlroots/pull/2505.

**Review by kennylevinsen — APPROVED** [review]

**Comment by kennylevinsen** [comment]
Thanks!

**Pull request merged**
