### PR TITLE
backend/session/libseat: pass wlroots log level to libseat

### PR DESCRIPTION
**Pull request by alebastr**
Trivial change to get more logs from libseat.
CC @kennylevinsen

### CODE REVIEW

**Comment by emersion** [comment]
I wonder if we really want to enable debug logs for all of our dependencies when wlroots is running in debug mode.

For instance, EGL never requests debug logs: https://github.com/swaywm/wlroots/blob/c5dad8b626539c0492f14075fec63bd0fb881e76/render/egl.c#L186

**Comment by alebastr** [comment]
Debug logs are disabled in release build of libseat. I'd assume that if someone is running debug libseat they expect to see these logs.

**Comment by emersion** [comment]
Oh, why are debug logs disabled in release builds? It makes it quite difficult for libseat users to ask their own users to get debug logs to investigate bugs.

**Comment by kennylevinsen** [comment]
> Oh, why are debug logs disabled in release builds?

Just an occupational injury. With the current amount of debug logging, I wouldn't be opposed to enabling it in release builds.

Most debug logging happens in the server though - I think the only instance of debug logging in libseat is around drm pause/unpause events in logind. Rest is info or error level.

> I wonder if we really want to enable debug logs for all of our dependencies when wlroots is running in debug mode.

We need the ability to set per-module loglevels. :/

**Comment by emersion** [comment]
Thanks for sending a PR, but I'd rather not configure our dependencies to enable debug logs.

**Pull request closed without merging**
