### PR TITLE
examples/gamma-control.c: add parameter to set different gamma for rgb

### PR DESCRIPTION
**Pull request by brandsimon**
I wanted to modify my gamma value for each rgb value, so I changed to code to enable this.
If there is only one value provided for r:g:b, it is backwards compatible.
I'm happy to adapt the PR, if there is anything needed to do for a merge.

### CODE REVIEW

**Comment by brandsimon** [comment]
I forgot to mention, I tested the values and they are exactly the same as with `xrandr --gamma r:g:b` on my system.

**Comment by ddevault** [comment]
The examples are just that: examples. Not meant for regular use. I would rather see this feature implemented in a more generic, standalone tool for adjusting gamma.

**Comment by brandsimon** [comment]
If it is just an example, why not merge it to show people, that this is possible.
People told me, that this is not possible yet with sway, but obviously, it is.
I agree, a standalone tool would be better.

**Comment by emersion** [comment]
This is an example for developers to test their compositor, not for end users. We don't want to add all possible features to examples.

**Comment by brandsimon** [comment]
I want to test my compositor to handle different gamma values for rgb correctly. :D
Never mind, thank you.

**Comment by brandsimon** [comment]
Hi,

I am creating a separate package for this tool and have two questions:
1. When I add a new display and enable it via sway, gamma is only changed on the old displays, not the newly connected one. Is this a sway issue or do I need to listen to this event and handle it? If so, is there an example which demonstrates how to listen to this event?

2. Needs the wlr-gamma-control-unstable-v1.xml be included in every tool or is there a package, where this should be included? Either sway nor wlroots are installing this file on my system. (Arch Linux)

**Comment by emersion** [comment]
This tool isn't supposed to get installed/packaged. It's just an example, it won't handle hotplug.

**Comment by brandsimon** [comment]
@emersion 
Exactly that's what I am doing, I found the solution for the first question.

**Comment by progandy** [comment]
https://github.com/swaywm/wlr-protocols
Since it isn't packaged, you could either copy it, use a git submodule or a git subtree.

This project might interest you: https://github.com/mherzberg/wlr-brightness

**Comment by emersion** [comment]
Ah, sorry, I misunderstood. Then yeah you need to listen for `wl_output` globals being added on the fly. And @progandy replied to the second question.

**Pull request closed without merging**
