### PR TITLE
Drop gtk-primary-selection support

### LINKED ISSUE #2421: Drop support for gtk-primary-selection
The last blocking consumer of gtk-primary-selection now supports the standard protocol: https://gitlab.gnome.org/GNOME/gtk/-/issues/2591#note_920637 (released in GTK 3.24.24).

- [x] Remove gtk-primary-selection from Sway
- [ ] Remove gtk-primary-selection from wlroots

### PR DESCRIPTION
**Pull request by ifreund**
The standard protocol is now widely supported.

Closes  #2421

### CODE REVIEW

**Comment by ifreund** [comment]
River commit: https://github.com/ifreund/river/commit/2b24e553756d5eb0d999f376890cf12ff8f7e19d

**Comment by emersion** [comment]
Sway dropped support for this protocol. Other compositors may have a less bleeding-edge approach, so will wait a few months before dropping this from wlroots.

**Comment by emersion** [comment]
Can you rebase this PR?

**Comment by ifreund** [comment]
> Can you rebase this PR?

done :)

**Review by emersion — APPROVED** [review]
Thanks!

**Pull request merged**
