### PR TITLE
Add fractional scaling support

### PR DESCRIPTION
**Pull request by emersion**
- [x] Fix wayland backend pointer events

Test plan:

```ini
[output:XXX]
scale = 1.5
```

Try various wayland and xwayland apps. Check rendering and input events. Try fullscreen.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
I know this says WIP, but I tested it anyway so here are my results.

I set scale=2.5 on a 4K output and got rendering artifacts and gedit crashes:

wayland-screenshot

**Comment by SirCmpwn** [comment]
I got similar results when scale=3 but not when scale=2. I wonder if it's a GTK bug...

**Comment by SirCmpwn** [comment]
Yeah, I can reproduce all of that on master as well.

**Comment by emersion** [comment]
Okay, so this isn't related to fractional scaling right? I only tested with scale=1.5. Does that work for you?

**Comment by SirCmpwn** [comment]
Yeah, 1.5 works. Sorry for the noise, I can reproduce the GTK issues on Weston too so I'll file a bug with them.

**Comment by emersion** [comment]
This PR is ready for review.

**Comment by SirCmpwn** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=791656

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
