### PR TITLE
Call pthread_sigmask() as early as possible so Xwayland SIGUSR1 is not caught by GPU driver threads

### PR DESCRIPTION
**Pull request by a-m-joseph**
Supersedes/replaces https://github.com/swaywm/sway/pull/4537

### CODE REVIEW

**Comment by emersion** [comment]
Hmm, this isn't a good place for this piece of code.

Can't the Mali driver ignore SIGUSR1?

**Comment by a-m-joseph** [comment]
> Hmm, this isn't a good place for this piece of code.
> 
> Can't the Mali driver ignore SIGUSR1?

No.

**Comment by emersion** [comment]
>No.

Why not?

**Comment by a-m-joseph** [comment]
> > No.
> 
> Why not?

This patch is how you make the Mali driver ignore SIGUSR1.

When a thread receives a signal it wasn't expecting, the process terminates. The way you indicate that the signal is not unexpected is by calling pthread_sigmask() before the thread is created, which is what both this patch and Weston do.

**Comment by emersion** [comment]
If there's no way to move this inside `wlr_xwayland`, I'd prefer this patch to be in sway's `main` function.

**Comment by agx** [comment]
> If there's no way to move this inside wlr_xwayland, I'd prefer this patch to be in sway's main function.

I agree. Messing with signal masks in the library will only cause more problems. We're   doing this in phoc

https://source.puri.sm/Librem5/phoc/blob/master/src/main.c#L116

to avoid having the wrong thread receive the signal.

**Comment by a-m-joseph** [comment]
> https://source.puri.sm/Librem5/phoc/blob/master/src/main.c#L116

In your code:

```
  sigprocmask(SIG_BLOCK, &mask, NULL);
```

$ man 2 sigprocmask
...
The use of **sigprocmask() is unspecified in a multithreaded process**; see pthread_sigmask(3). 
...

**Comment by ddevault** [comment]
Mali is in the wrong here. They should not be doing this.

**Comment by ascent12** [comment]
Yeah, I don't see why Mali would have issues with this, yet many of the Mesa drivers (which are multithreaded) don't.
We've have next to no interest in supporting proprietary drivers. It's fine if they happen to work with standard interfaces or with things like GBM, but going out of our way to have workarounds for them is not something I want to carry. That's not even something I would want to do with an open driver.

**Comment by ddevault** [comment]
>We've have next to no interest in supporting proprietary drivers

I would say we have *less* than zero interest.

**Comment by a-m-joseph** [comment]
> They should not be doing this.

Not be doing what, exactly?

**Pull request closed without merging**
