### PR TITLE
layer_shell: set layer of existing surface

### PR DESCRIPTION
**Pull request by Timidger**
[Implementation in Way Cooler](https://github.com/way-cooler/way-cooler/pull/649)

### CODE REVIEW

**Comment by emersion** [comment]
Can you send a wlr-protocols PR too?

**Comment by Timidger** [comment]
[Done](https://github.com/swaywm/wlr-protocols/pull/59)

**Comment by emersion** [comment]
Looks good to me overall, waiting on wlr-protocols

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
