### PR TITLE
Fix glgen to be more POSIX corformant

### PR DESCRIPTION
**Pull request by ascent12**
I tried running this with dash (used by debian/ubuntu for their /bin/sh) and apparently this wasn't conforming.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
How about more like

```sh
case $COMMAND in
    -*)
        # ...
        ;;
    *WL)
        ;;
esac
```

**Comment by SirCmpwn** [comment]
[POSIX shell specification](http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html)

**Comment by ascent12** [comment]
I suppose that would work, but it's awfully verbose. Also, would -eglFooBarWL execute both of them?

**Comment by emersion** [comment]
[Shellcheck](https://github.com/koalaman/shellcheck) is pretty good at catching this kind of issues (there's a POSIX mode).

**Comment by SirCmpwn** [comment]
More verbose than defining two functions? More intented, perhaps. And yes, but are we going to do that?

**Comment by ascent12** [comment]
-eglUnbindWaylandDisplayWL is there currently, although it would be easy to argue that a lot of the "optional" things there really shouldn't be optional.

**Comment by SirCmpwn** [comment]
How about making it more POSIXY in general? `mandatory mandatory -o optional mandatory`

**Comment by SirCmpwn** [comment]
(though strictly speaking POSIX specifies all options come before arguments)

**Comment by ascent12** [comment]
It didn't turn out as verbose as I thought it would.
I don't think it's worth messing with the arguments. Meson was giving me shit when I tried to build both the .c and .h in the same script, so I made them separate.

**Pull request merged**
