### PR TITLE
Fix crash in screencopy dmabuf and fix black buffer blits

### PR DESCRIPTION
**Pull request by emersion**
_See each commit._

cc @bl4ckb0ne @any1

### CODE REVIEW

**Comment by any1** [comment]
It could be moved into `render/wlr_renderer.c` instead. Right?

**Comment by emersion** [comment]
Could, but nobody else needs it right now.

**Comment by any1** [comment]
But shouldn't then `wlr_renderer_blit_dmabuf` be removed?

**Comment by emersion** [comment]
Done in https://github.com/swaywm/wlroots/pull/2789, submitted as a separate PR because that's a breaking change.

**Comment by J0nnyMak0** [comment]
Yes, this fixes https://github.com/swaywm/wlroots/issues/2780 for me. Thanks!

**Pull request merged**
