### PR TITLE
Ignore emacs backup files

### PR DESCRIPTION
**Pull request by agx**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
https://www.emacswiki.org/emacs/BackupDirectory

**Comment by agx** [comment]
@SirCmpwn I know but vim swap files are being ignored as well so it makes things simpler for folks that haven't tweaked things (or that clone/build wlroots on a system with not much emacs setup)

**Comment by SirCmpwn** [comment]
https://github.com/swaywm/wlroots/commit/ab738256ac3cdaadb33dcd6d59accc876c45a51a

**Comment by Timidger** [comment]
You could also just add it to your global git ignore file, like what I do.

**Pull request closed without merging**
