### PR TITLE
surface: don't cache frame callback lists

### PR DESCRIPTION
**Pull request by vyivel**
While the compositor may render the locked state, it still needs to make clients think their latest state is being rendered. Achieve that by not caching frame callback lists.

### CODE REVIEW

**Comment by vyivel** [comment]
cc @ammen99

**Review by ammen99 — COMMENTED** [review]
Tested this and seems to work in Wayfire, so LGTM.

In case someone wonders, we're sending the frame events inside the cache event handler (in case that the desired state is not reached yet), and of course on `wlr_output.frame`

**Review by emersion — APPROVED** [review]
LGTM as well, thanks!

**Comment by vyivel** [comment]
Ah, there was a typo in the comment. Sorry about that.

**Pull request merged**
