### PR TITLE
Set compositor cursor for move, resize and rotate

### PR DESCRIPTION
**Pull request by emersion**
Test plan:
- Move a window with its border or with the meta key, check that the cursor is a hand
- Resize a window from each edge, check cursor
- Rotate a window, check cursor
- Make sure the surface cursor is used when move/resize/rotate ends

Updates #342

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Can you establish rootston/xcursor to encapsulate all of the xcursor logic? I have more stuff coming for the HiDPI branch that would benefit from this, too.

**Comment by SirCmpwn** [comment]
Move a window with its border or with the meta key, check that the cursor is a hand: **PASS**

Resize a window from each edge, check cursor **FAIL**

Rotate a window, check cursor  **PASS** assuming the cursor is supposed to be the grabby hand

Make sure the surface cursor is used when move/resize/rotate ends **PASS**

**Comment by emersion** [comment]
>Resize a window from each edge, check cursor: FAIL

I cannot reproduce. Tested on both `weston-terminal` and `nautilus`. What client are you testing this with?

**Comment by SirCmpwn** [comment]
gnome-terminal. Do you mean a shell-induced resize? I'm resizing with mod+rmouse somewhere in the middle of the view.

**Comment by emersion** [comment]
Okay, so this should always resize with the bottom-right edge, with the appropriate cursor. This PR doesn't solve #342, it just solves the cursor part of it. Resizing with the meta key from all edges is somewhat unrelated and will be done in another PR.

**Comment by SirCmpwn** [comment]
Aight

**Pull request merged**
