### PR TITLE
Split xdg-shell into multiple files

### PR DESCRIPTION
**Pull request by emersion**
I had to rename xdg-shell-unstable-v6 functions because of conflicts with xdg-shell stable (both the generated Wayland protocol code and the new private functions).

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Breaking changes

**Comment by Ongy** [comment]
Are they really breaking changes? Nothing under `include/wlr/` changed, just `include/types/`, so it should be internal changes.

And just skimming the diffs, it looks like mostly "if it compiles, it works" changes, should I do indepth review?

**Comment by emersion** [comment]
>Are they really breaking changes? Nothing under include/wlr/ changed, just include/types/, so it should be internal changes.

Removed one function which was incorrectly used on popups with a layer surface parent.

>And just skimming the diffs, it looks like mostly "if it compiles, it works" changes, should I do indepth review?

Mostly. I also tested it to make sure assertions still hold, but yeah, there are no logic changes.

**Comment by emersion** [comment]
Bump

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
