### PR TITLE
Introduce wlr_drm_lease_v1

### PR DESCRIPTION
**Pull request by Zamundaaa**
This is mostly a rebase of https://github.com/swaywm/wlroots/pull/1730 with the protocol updated and its changes applied to the code

### CODE REVIEW

**Comment by sjnewbury** [comment]
@Zamundaaa Something is weird here.  I mentioned on the previous revision about the properties index, but somehow it's still broken.  The last entry isn't getting read.  If I move non-desktop above vrr_capable it works fine, otherwise non_desktop never gets set for the connection.

**Comment by Zamundaaa** [comment]
That's very odd, it up but it's supposed to work either way... I'll move it up

**Comment by sjnewbury** [comment]
> That's very odd, it's supposed to work either way... I'll move it up

Obviously it should work, but it won't because: -

in scan_properties():
`
for (uint32_t i = 0; i < props->count_props; ++i) {
                                 ^ last property never gets read`

**Comment by progandy** [comment]
> That's very odd, it's supposed to work either way... I'll move it up

https://github.com/swaywm/wlroots/blob/e31d7bcf37e09ad3b57542c1b9d1bdabcba042b9/backend/drm/properties.c#L12-L14

The array has to be sorted according to strcmp. That basically means alphabetically, but an uppercase letter comes before any lowercase letter, so ```CRTC_ID,DPMS,EDID,PATH,link-status,non-desktop,subconnector,vrr_capable```

**Comment by emersion** [comment]
TBH, we could just remove this restriction. Reading the properties is a step done once at initialization so it's not in a hot path anyway.

**Comment by sjnewbury** [comment]
@Zamundaaa, so I've been trying to get this all working with the latest patches across the stack, but I'm getting this error whilst starting monado-service:

`wl_display@1: error 1: invalid arguments for zwp_drm_lease_request_v1@3.submit`

So instead of using the patches on top of my own versions, I checked out every relevant branch (as listed: https://gitlab.freedesktop.org/lubosz/wlxr-pkgbuilds ), and it made no difference.

My only guess is the protocol definition contained in one of the repos is a different version?  Presumably, it should all work?

**Comment by Zamundaaa** [comment]
> My only guess is the protocol definition contained in one of the repos is a different version?

That is correct, the one in the Mesa patch needs updating. The incompatible change is that the lease request will be destroyed by the compositor on submit instead of having an explicit destructor, so you need to copy over the latest protocol and delete the call to zwp_drm_lease_request_v1_destroy.

**Comment by sjnewbury** [comment]
> > My only guess is the protocol definition contained in one of the repos is a different version?
> 
> That is correct, the one in the Mesa patch needs updating. The incompatible change is that the lease request will be destroyed by the compositor on submit instead of having an explicit destructor, so you need to copy over the latest protocol and delete the call to zwp_drm_lease_request_v1_destroy.

Thanks! that's the only one I hadn't checked!  It's running now with the xrgears demo from the monado repo.  Now it's just Xwayland that doesn't seem to be working... (not showing up in xrandr)

**Comment by sjnewbury** [comment]
> > > My only guess is the protocol definition contained in one of the repos is a different version?
> > 
> > 
> > That is correct, the one in the Mesa patch needs updating. The incompatible change is that the lease request will be destroyed by the compositor on submit instead of having an explicit destructor, so you need to copy over the latest protocol and delete the call to zwp_drm_lease_request_v1_destroy.
> 
> Thanks! that's the only one I hadn't checked! It's running now with the xrgears demo from the monado repo. Now it's just Xwayland that doesn't seem to be working... (not showing up in xrandr)

xrandr shows only:
 `Screen 0: minimum 16 x 16, current 1920 x 1080, maximum 32767 x 32767
XWAYLAND0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 1290mm x 720mm
   1920x1080     59.96*+
...
XWAYLAND1 disconnected (normal left inverted right x axis y axis)`
whether or not the headset is powered on.  XWAYLAND1 disappears if monado-service is running (as expected presumably).

SteamVR with the monado plugin reports server not responding (or similar) and never starts.

**Comment by Zamundaaa** [comment]
> XWAYLAND1 disconnected

That's the headset. You can check with `xrandr --verbose`.

>  XWAYLAND1 disappears if monado-service is running (as expected presumably).

Yes, that is intended behavior, the connector gets withdrawn when it's leased.

Not sure what's going on with the monado plugin but once the output is leased everything is responsibility of the client, so it's probably a bug in Monado.

**Comment by sjnewbury** [comment]
Okay, you're right, randr is working as far as showing output information with --verbose.

Also, I managed to get the plugin sort of working with SteamVR, but couldn't get the headset screen to light up. It detects tracking data and the controller.

Is there a simple test program for X11 drm-leasing where I can lease an output and get the screen to light up?

**Comment by Zamundaaa** [comment]
> Is there a simple test program for X11 drm-leasing where I can lease an output and get the screen to light up?

Isn't xrgears that? You could also use monado without the patch, it should use the X11 mode then.

**Comment by sjnewbury** [comment]
> > Is there a simple test program for X11 drm-leasing where I can lease an output and get the screen to light up?
> 
> Isn't xrgears that? You could also use monado without the patch, it should use the X11 mode then.

After figuring out Steam had set my default OpenXR runtime with their OpenVR and broken xrgears against monado I've done some more testing:

All using PSVR/OpenHMD hidapi-libusb Radeon RX470 (Gaming X)

- Under Wayland using monado with the Wayland patch it works well with one caveat, see below ++.
- Under Wayland through Xwayland, no modes show up (and it seems no modesetting occurs) with xrandr --verbose
`XWAYLAND1 disconnected (normal left inverted right x axis y axis)
	Identifier: 0x1c4
	Timestamp:  104209
	Subpixel:   unknown
	Clones:
	CRTCs:      1
	Transform:  1.000000 0.000000 0.000000
	            0.000000 1.000000 0.000000
	            0.000000 0.000000 1.000000
	           filter:
	CONNECTOR_ID: 85
		supported: 85
	non-desktop: 1
		supported: 0, 1`
- Under Xorg it works perfectly. xrandr --verbose shows "non-desktop: 1", and gives available modes

++ When using monado/xrgears under Wayland monado reports that it is missing the frame deadline, and indeed this is visble on the headset as a shudder while moving.  Xorg, this doesn't happen.  It seems strange for there to be any performance difference between drm-leasing under Wayland or Xorg, and certainly for Wayland (sway) to be slower.  Now, it's quite possible my hardware might be struggling to reach 1920x1080@120Hz, although I don't think it should have a problem with the xrgears test scene.  Maybe it's just syncing to vblank on Xorg and trying to match the vertical refresh rate on Wayland?

**Comment by Zamundaaa** [comment]
Do you perhaps get any of the error messages in the lines above [here](https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/606/diffs#f3bb4fe824066c75982a913523168d9eacd57f87_876_1050)? Anyways, this should probably be discussed on the Xwayland patch - although it works flawlessly for me someone else had a problem with the modes as well.

> When using monado/xrgears under Wayland monado reports that it is missing the frame deadline, and indeed this is visble on the headset as a shudder while moving. Xorg, this doesn't happen

No clue what that could be caused by - the underlying code in Monado and Mesa that runs after the lease is acquired should be 1:1 the same as on X.

**Comment by sjnewbury** [comment]
I'll reply to the modes issue on the Xwayland PR. I have a theory what's happening..

> 
> > When using monado/xrgears under Wayland monado reports that it is missing the frame deadline, and indeed this is visble on the headset as a shudder while moving. Xorg, this doesn't happen
> 
> No clue what that could be caused by - the underlying code in Monado and Mesa that runs after the lease is acquired should be 1:1 the same as on X.

It's definitely slower - or timing is slightly worse on Sway vs Xorg.  This is really weird.  The only thing I can think of is maybe VRAM allocation is different?  I only have a 4G card, and UHD main display, then the headset, perhaps there's system memory getting used under Wayland when running the demo but not under Xorg?

**Comment by Scrumplex** [comment]
I can successfully start SteamVR and see stuff on my HMD. Now if I close SteamVR (gracefully, that is) and restart it, SteamVR does not find the HMD anymore.

Looking at `xrandr --verbose`

 1. Before starting SteamVR: has `XWAYLAND2` (HMD)
 2. After starting SteamVR: no `XWAYLAND2` (expected)
 3. After closing SteamVR: no `XWAYLAND2`
 4. After starting SteamVR again: Direct Mode disabled, log shows `Tried to find direct display through RandR: (nil)`

So it looks like XWayland is either not destroying it's lease, or this implementation does not properly destruct the lease.

**Comment by Scrumplex** [comment]
Also change the title of the MR: `s/wlr_/wp_/g`

**Comment by Scrumplex** [comment]
I get this output when closing SteamVR
```
00:00:54.160 [DEBUG] [sway/desktop/transaction.c:294] Applying transaction 0x56096eafac70
00:00:54.160 [DEBUG] [wlr] [backend/drm/drm.c:1664] Terminating DRM lease 1
00:00:54.160 [INFO] [wlr] [backend/drm/drm.c:1249] Scanning DRM connectors on /dev/dri/card0
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1105] Reallocating CRTCs
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1116] State before reallocation:
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1122]   'DP-1' crtc=0 state=3 desired_enabled=1
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1122]   'DP-2' crtc=1 state=3 desired_enabled=1
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1122]   'DP-3' crtc=-1 state=1 desired_enabled=1
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1122]   'HDMI-A-1' crtc=-1 state=0 desired_enabled=0
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1122]   'HDMI-A-2' crtc=-1 state=0 desired_enabled=0
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1122]   'HDMI-A-3' crtc=-1 state=0 desired_enabled=0
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1173] State after reallocation:
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1180]   'DP-1' crtc=0 state=3 desired_enabled=1
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1180]   'DP-2' crtc=1 state=3 desired_enabled=1
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1180]   'DP-3' crtc=5 state=1 desired_enabled=1
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1180]   'HDMI-A-1' crtc=-1 state=0 desired_enabled=0
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1180]   'HDMI-A-2' crtc=-1 state=0 desired_enabled=0
00:00:54.162 [DEBUG] [wlr] [backend/drm/drm.c:1180]   'HDMI-A-3' crtc=-1 state=0 desired_enabled=0
00:00:54.162 [DEBUG] [wlr] [types/wlr_drm_lease_v1.c:160] drm_terminate_lease: Inappropriate ioctl for device
(EE)00:00:54.162 [DEBUG] [sway/desktop/layer_shell.c:343] Layer surface destroyed (wallpaper) 
failed to read Wayland events: Connection reset by peer
00:00:54.162 [DEBUG] [sway/desktop/layer_shell.c:343] Layer surface destroyed (wallpaper)
```

**Comment by Scrumplex** [comment]
I was trying to look into this again but I can't find whats wrong here.

[`sway -d 2> swaylog.txt`](https://github.com/swaywm/wlroots/files/6489634/swaylog.txt)


```
  2602	00:00:29.556 [DEBUG] [wlr] [backend/drm/drm.c:1631] Issuing DRM lease with the 4 objects:
  2603	00:00:29.556 [DEBUG] [wlr] [backend/drm/drm.c:1638] connector: 88 crtc: 75 primary plane: 40
  2604	00:00:29.556 [DEBUG] [wlr] [backend/drm/drm.c:1641] cursor plane: 73
  2605	00:00:29.556 [DEBUG] [wlr] [backend/drm/drm.c:1650] Issued DRM lease 9 1                                        <--
  2606	00:00:29.556 [DEBUG] [wlr] [backend/drm/drm.c:1079] connector DP-3: De-allocating CRTC 5
--
 11763	00:00:52.408 [DEBUG] [sway/desktop/transaction.c:398] Transaction 0x56101ac48000 committing with 2 instructions
 11764	00:00:52.408 [DEBUG] [sway/desktop/transaction.c:294] Applying transaction 0x56101ac48000
 11765	00:00:52.408 [DEBUG] [wlr] [backend/drm/drm.c:1664] Terminating DRM lease 9 1                                   <--
 11766	00:00:52.408 [DEBUG] [wlr] [backend/drm/drm.c:1668] lease revoke ret -2                                         <--
 11767	00:00:52.408 [INFO] [wlr] [backend/drm/drm.c:1249] Scanning DRM connectors on /dev/dri/card0
 11768	00:00:52.409 [DEBUG] [wlr] [backend/drm/drm.c:1105] Reallocating CRTCs
--
 11780	00:00:52.409 [DEBUG] [wlr] [backend/drm/drm.c:1180]   'HDMI-A-1' crtc=-1 state=0 desired_enabled=0
 11781	00:00:52.409 [DEBUG] [wlr] [backend/drm/drm.c:1180]   'HDMI-A-2' crtc=-1 state=0 desired_enabled=0
 11782	00:00:52.409 [DEBUG] [wlr] [backend/drm/drm.c:1180]   'HDMI-A-3' crtc=-1 state=0 desired_enabled=0
 11783	00:00:52.409 [DEBUG] [wlr] [types/wlr_drm_lease_v1.c:161] drm_terminate_lease: Inappropriate ioctl for device   <--
 11784	00:00:00.909 00:00:52.088 [ERROR] (EE)[ERROR] [common/ipc-client.c:87] Unable to receive IPC response [common/ipc-client.c:87] Unable to receive IPC response
 11785	failed to read Wayland events: Broken pipe
 11786	
```

1. lease gets issued in line 2605: `Issued DRM lease 9 1`
2. lease gets terminated in line 11765: `Terminating DRM lease 9 1`
3. drmModeRevokeLease returns `-2` in line 11766: `lease revoke ret -2`
4. revoke fails in line 11783 `drm_terminate_lease: Inappropriate ioctl for device`

The messages in 1., 2. and 3. are from my own debugging by printing.
These are how those outputs are generated
```diff
diff --git a/backend/drm/drm.c b/backend/drm/drm.c
index 2c8e693f3c127375..232010f1bea19079 100644
--- a/backend/drm/drm.c
+++ b/backend/drm/drm.c
@@ -1647,7 +1647,7 @@ int drm_create_lease(struct wlr_drm_backend *backend,
        if (lease_fd < 0) {
                return lease_fd;
        }
-       wlr_log(WLR_DEBUG, "Issued DRM lease %d", *lessee_id);
+       wlr_log(WLR_DEBUG, "Issued DRM lease %d %d", backend->fd, *lessee_id);
        for (int i = 0; i < nconns; ++i) {
                struct wlr_drm_connector *conn = conns[i];
                conn->lessee_id = *lessee_id;
@@ -1661,8 +1661,12 @@ int drm_create_lease(struct wlr_drm_backend *backend,
 }
 
 int drm_terminate_lease(struct wlr_drm_backend *backend, uint32_t lessee_id) {
-       wlr_log(WLR_DEBUG, "Terminating DRM lease %d", lessee_id);
+       wlr_log(WLR_DEBUG, "Terminating DRM lease %d %d", backend->fd, lessee_id);
+
        int r = drmModeRevokeLease(backend->fd, lessee_id);
+
+       wlr_log(WLR_DEBUG, "lease revoke ret %d", r);
+
        struct wlr_drm_connector *conn;
        wl_list_for_each(conn, &backend->outputs, link) {
                if (conn->state == WLR_DRM_CONN_LEASED
```
As you can see the fds as well as the lessee_ids match in both cases. I don't see why DRM is giving us a ENOENT here

**Comment by bl4ckb0ne** [comment]
@Scrumplex you're leasing a valid connector from the wrong drm fd. There's an issue with the implementation where the fd of card0 is advertised, but all of the connectors from all of the cards are advertised.

 I am working on the issue ana should send a more up to date version soon.

**Comment by Zamundaaa** [comment]
@bl4ckb0ne as leasing the first time works it probably is not exactly the same issue; it probably is still related though.

Will you take over this and make a MR yourself? Then I'll close this one.

**Comment by bl4ckb0ne** [comment]
I'll take over this and the implementation in sway yes. You can close the pull requests, I'll make them as soon as I have something that works.

**Pull request closed without merging**
