### PR TITLE
Make seat backend optional

### PR DESCRIPTION
**Pull request by DemiMarie**
It adds a dependency on libseat and not all compositors need it.

### CODE REVIEW

**Comment by DemiMarie** [comment]
@emersion It allows building a smaller binary, and reduces the total size of the dependency tree for those (such as Qubes OS) who will only be using software rendering and virtual inputs.

**Comment by DemiMarie** [comment]
> `-Dsession=disabled` doesn't need libudev as well, see #2257. This may help NetBSD and OpenBSD to make an initial port of wlroots as nested-only + headless-only.

I can see a rootless nested backend being quite useful in practice.

**Comment by DemiMarie** [comment]
> I don't really buy the "smaller binary" argument, libseat is a few KiBs on my system, probably even less with everything disabled.

That is still a bit less code, and for projects that need to review all of the code they use, it is less code to review.

**Comment by emersion** [comment]
Yes, I haven't considered the udev dependency, and it's definitely a good point.

**Comment by emersion** [comment]
wlroots has migrated to gitlab.freedesktop.org. This pull request has been moved to:

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3256

**Pull request closed without merging**
