### PR TITLE
misc keyboard fixes

### PR DESCRIPTION
**Pull request by acrisci**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
What remains to be done here? Which problems does this fix?

**Comment by acrisci** [comment]
It fixes all of the xkb memory leaks.

There is also a global destroy event on wlr-output that @emersion forgot to remove that's fixed here that fixes a segfault on exit.

**Comment by SirCmpwn** [comment]
derp, missed @emersion's comment

**Comment by acrisci** [comment]
Oh how did that not cause problems for me...

**Comment by emersion** [comment]
Probably because the free'd block still contained the old data by chance.

**Pull request merged**
