### PR TITLE
render: fix EGL extensions not loaded

### PR DESCRIPTION
**Pull request by emersion**
Some extensions are only advertised by the EGL implementation with a
non-zero EGLDisplay. That's the case when the extension can only be
enabled when the hardware/driver supports it for instance.

Instead of checking for all extensions without a display, check only for
EGL_EXT_platform_base and EGL_KHR_debug which are used before
eglGetDisplay. Check for all other extensions when we have a display.

Closes: https://github.com/swaywm/wlroots/issues/1955
Closes: https://github.com/swaywm/sway/issues/4828

### CODE REVIEW

**Comment by kchibisov** [comment]
Seems like it's working fine. At least the beginning of the debug logs from sway are ~identical now.

log after your patch.
[sway_patched.log](https://github.com/swaywm/wlroots/files/3989073/sway_patched.log)

**Comment by ddevault** [comment]
That arch failure is weird.

**Comment by emersion** [comment]
It's an arch packaging issue:

```
export PKG_CONFIG_DEBUG_SPEW=1
pkg-config x11-xcb
Package xproto was not found in the pkg-config search path.
Perhaps you should add the directory containing `xproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xproto', required by 'x11', not found
Package 'kbproto', required by 'x11', not found
```

**Comment by emersion** [comment]
Reported here: https://bugs.archlinux.org/task/64914

**Comment by JonnyMako** [comment]
I can confirm that this branch fixes https://github.com/swaywm/sway/issues/4828

**Comment by ppascher** [comment]
This also fixes vulkan not working since commit 515679e4fed1c7c762a8c269fca09cbb195a4323. Various extensions were not detected, swapchain could not be created (steam, vkcube).

**Comment by ddevault** [comment]
Can you rebase this?

**Comment by emersion** [comment]
Done

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
