### PR TITLE
Reset pointer focus on surface commit

### PR DESCRIPTION
**Pull request by fwSmit**
This should fix https://github.com/swaywm/sway/issues/5911. I want to test it, but I don't know how to. Do I need to recompile sway before testing? Most of the examples don't run (see #2580), so I can't test those.

### CODE REVIEW

**Comment by ammen99** [comment]
I don't like this, wouldn't this be racy with the compositor updating focus on commit?

**Comment by fwSmit** [comment]
I didn't know that was a job for the compositor. I'm not familiar with the codebase. The focus change on surface destroy is handled by wlroots thought (which is where I copied it from).

**Comment by ammen99** [comment]
@fwSmit Yes, the compositor is responsible for setting and clearing the focus. In the case that a surface is unmapped, it is a bit different because the surface cannot continue to be focus anyway and the compositor has to set another focus.

**Comment by fwSmit** [comment]
Alright, thanks for the info. This PR can be closed then.

**Pull request closed without merging**
