### PR TITLE
util/log: improve time prefix

### PR DESCRIPTION
**Pull request by emersion**
This is useful when debugging a rendering loop.

### CODE REVIEW

**Comment by emersion** [comment]
BTW, maybe we should consider dropping the current date (the YYYY-MM-DD part) to get a smaller log prefix.

**Comment by ddevault** [comment]
>BTW, maybe we should consider dropping the current date (the YYYY-MM-DD part) to get a smaller log prefix.

Agreed. Maybe we should log a monotonic clock in terms of seconds since the compositor began?

**Comment by emersion** [comment]
Good idea, changed the commit to do that.

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
