### PR TITLE
gamma-control-v1: apply gamma LUT when output gets enabled

### PR DESCRIPTION
**Pull request by emersion**
~~Depends on https://github.com/swaywm/wlroots/pull/2315~~

Closes: https://github.com/swaywm/wlroots/issues/2372

### CODE REVIEW

**Comment by emersion** [comment]
Doesn't actually work.

**Comment by ammen99** [comment]
What is the status of this? I am also getting the following crash:

```
EE 18-09-20 14:39:34.667 - [src/main.cpp:244] Fatal error: Fatal error(SIGABRT)
EE 18-09-20 14:39:34.799 - #1  signal_handler(int) ../src/main.cpp:246
EE 18-09-20 14:39:34.824 - #2  __restore_rt sigaction.c:?
EE 18-09-20 14:39:34.845 - #3  __GI_raise :?
EE 18-09-20 14:39:34.866 - #4  __GI_abort :?
EE 18-09-20 14:39:34.886 - #5  _nl_load_domain.cold loadmsgcat.c:?
EE 18-09-20 14:39:34.907 - #6  .annobin_assert.c_end assert.c:?
EE 18-09-20 14:39:34.919 - #7  gles2_get_renderer_in_context ../render/gles2/renderer.c:36
EE 18-09-20 14:39:34.932 - #8  gles2_bind_buffer ../render/gles2/renderer.c:138
EE 18-09-20 14:39:34.944 - #9  wlr_renderer_bind_buffer ../render/wlr_renderer.c:48
EE 18-09-20 14:39:34.956 - #10 drm_surface_unset_current ../backend/drm/renderer.c:161
EE 18-09-20 14:39:34.969 - #11 drm_connector_rollback_render ../backend/drm/drm.c:602
EE 18-09-20 14:39:34.984 - #12 wlr_output_rollback ../types/wlr_output.c:656
EE 18-09-20 14:39:34.998 - #13 gamma_control_handle_set_gamma ../types/wlr_gamma_control_v1.c:111
EE 18-09-20 14:39:35.009 - #14 ffi_call_unix64 ??:?
EE 18-09-20 14:39:35.017 - #15 ffi_call ??:?
EE 18-09-20 14:39:35.024 - #16 wl_event_loop_get_destroy_listener ??:?
EE 18-09-20 14:39:35.032 - #17 wl_client_destroy ??:?
EE 18-09-20 14:39:35.039 - #18 wl_event_loop_dispatch ??:?
EE 18-09-20 14:39:35.046 - #19 wl_display_run ??:?
EE 18-09-20 14:39:35.094 - #20 main ../src/main.cpp:409
EE 18-09-20 14:39:35.115 - #21 __libc_start_main ??:?
EE 18-09-20 14:39:35.140 - #22 ?? ??:0
```

I suppose this PR should fix it?

**Comment by crocket** [comment]
I hope this PR is merged soon as my eyes hurt at night without gammastep.

**Comment by emersion** [comment]
Current status is that the DRM backend doesn't set `wlr_output.frame_pending` correctly after enabling an output so this patch doesn't work.

**Comment by emersion** [comment]
https://github.com/swaywm/wlroots/pull/2459 should fix this.

**Review by ammen99 — APPROVED** [review]
LGTM and I think this commit fixes my crash, as I was having that problem when gamma is set while the output is disabled.

**Comment by emersion** [comment]
While this fixes the original issue, on Sway this doesn't quite work, because Sway calls `wlr_output_rollback` in-between frames for some reason. But this PR should at least fix the failure (and the whole issue on other compositors).

**Pull request merged**
