### PR TITLE
Fix moving views when resizing below min size

### LINKED ISSUE #357: Resizing below min size moves window with the mouse
Does not affect the lower-right corner. All shells are affected.

The lower-right corner is the right behavior. It should just stop resizing and not move around.

### PR DESCRIPTION
**Pull request by emersion**
Fixes #357

### CODE REVIEW

**Comment by emersion** [comment]
This PR is ready for review. Note that resizing from the top-left corner is still de-synchronized (first the window moves, then it is resized), I'll fix that in another PR.

**Comment by SirCmpwn** [comment]
Test plan?

**Comment by emersion** [comment]
Oh sorry, forgot to add it.

Test plan: resize a window from the top-left corner below the minimum size (and beyond). It shouldn't move.

`weston-terminal` doesn't set a min size, so that doesn't work. That'll be fixed with the other PR I referred to in my previous comment.

**Comment by SirCmpwn** [comment]
What's a good client to test with (that has a minimum size)?

**Comment by emersion** [comment]
Resizable GTK apps under XWayland and Wayland are good test cases (I used `gnome-dictionary`).

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
