### PR TITLE
subsurface: handle NULL parent in get_root_surface

### LINKED ISSUE #2542: KRDC VNC client crashes sway
**Description:**
@emersion based on the stacktrace crash happens in wlroots. What can I do to get more info?

Steps to reproduce

1. start kvm guest with `--graphics vnc` (most likely irrelevant, should work with any other vnc endpoint)
2. run [KRDC](https://apps.kde.org/en/krdc) and connect to vnc on localhost
3. enter full screen mode in KRDC
4. from full screen mode press "disconnect"
5. Observe segmentation failure

### System Info
- Gentoo
- `sway version 1.5.1` [ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/gui-wm/sway/sway-1.5.1.ebuild)
- `wlroots-0.12.0` [ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/gui-libs/wlroots/wlroots-0.12.0.ebuild)

- **Debug Log:** (TBD)
>  - Run `sway -d 2> ~/sway.log` from a TTY and upload it to a pastebin, such as gist.github.com.
>  - This will record information about sway's activity. Please try to keep the reproduction as brief as possible and exit sway.

- **Configuration File:**
default

- **Stack Trace:**
See below

### PR DESCRIPTION
**Pull request by ifreund**
Closes #2542

@ngortheone could you test this?

### CODE REVIEW

**Comment by ngortheone** [comment]
sure

**Comment by ngortheone** [comment]
@ifreund crashes in a different place now

```
Core was generated by `sway'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f553d7b9b10 in wl_list_insert () from /usr/lib64/libwayland-server.so.0
[Current thread is 1 (Thread 0x7f553cbae9c0 (LWP 789040))]
(gdb) bt full
#0  0x00007f553d7b9b10 in wl_list_insert () at /usr/lib64/libwayland-server.so.0
#1  0x0000555b39a4c433 in wl_signal_add (listener=0x555b3c18c680, signal=0x555b3c17b0c8) at /usr/include/wayland-server-core.h:441
        workspace = <optimized out>
#2  view_child_init (child=child@entry=0x555b3c18c5c0, impl=impl@entry=0x555b39a6eb10 <subsurface_impl>, view=0x555b3c17afe0, surface=0x555b3c18b560)
    at ../sway-1.5.1/sway/tree/view.c:997
        workspace = <optimized out>
#3  0x0000555b39a4c5a5 in view_child_subsurface_create (wlr_subsurface=0x555b3c18c9a0, child=0x555b3c189d70) at ../sway-1.5.1/sway/tree/view.c:898
        subsurface = 0x555b3c18c5c0
        child = 0x555b3c189d70
        subsurface = 0x555b3c18c9a0
#4  view_child_handle_surface_new_subsurface (listener=0x555b3c189dd0, data=0x555b3c18c9a0) at ../sway-1.5.1/sway/tree/view.c:932
        child = 0x555b3c189d70
        subsurface = 0x555b3c18c9a0
#5  0x00007f553d775c72 in wlr_signal_emit_safe (signal=signal@entry=0x555b3c189b50, data=data@entry=0x555b3c18c9a0) at ../wlroots-0.12.0/util/signal.c:29
        pos = 0x555b3c189dd0
        l = 0x555b3c189dd0
        cursor = {link = {prev = 0x555b3c189dd0, next = 0x7ffe492e4830}, notify = 0x7f553d775bff <handle_noop>}
        end = {link = {prev = 0x7ffe492e4810, next = 0x555b3c189b50}, notify = 0x7f553d775bff <handle_noop>}
#6  0x00007f553d770d2d in wlr_subsurface_create
    (surface=surface@entry=0x555b3c18b560, parent=parent@entry=0x555b3c189810, version=<optimized out>, id=id@entry=78, resource_list=resource_list@entry=0x0)
    at ../wlroots-0.12.0/types/wlr_surface.c:1043
        __PRETTY_FUNCTION__ = "wlr_subsurface_create"
        client = 0x555b3c16cea0
        subsurface = 0x555b3c18c9a0
        resource_link = <optimized out>
#7  0x00007f553d75cacf in subcompositor_handle_get_subsurface
    (client=<optimized out>, resource=0x555b3c16eca0, id=78, surface_resource=0x555b3c18b910, parent_resource=<optimized out>)
    at ../wlroots-0.12.0/types/wlr_compositor.c:69
        surface = 0x555b3c18b560
        parent = 0x555b3c189810
        msg = "get_subsurface: wl_subsurface@"
#8  0x00007f553d175eed in  () at /usr/lib64/libffi.so.7
#9  0x00007f553d17532a in  () at /usr/lib64/libffi.so.7
#10 0x00007f553d7b925d in  () at /usr/lib64/libwayland-server.so.0
#11 0x00007f553d7b5817 in  () at /usr/lib64/libwayland-server.so.0
#12 0x00007f553d7b7432 in wl_event_loop_dispatch () at /usr/lib64/libwayland-server.so.0
#13 0x00007f553d7b5a05 in wl_display_run () at /usr/lib64/libwayland-server.so.0
#14 0x0000555b39a19df9 in server_run (server=server@entry=0x555b39a70ea0 <server>) at ../sway-1.5.1/sway/server.c:234
#15 0x0000555b39a197cb in main (argc=1, argv=0x7ffe492e5018) at ../sway-1.5.1/sway/main.c:410
```

**Comment by ifreund** [comment]
> @ifreund crashes in a different place now

That stack trace seems to point to a sway bug rather than a wlroots bug. Determining exactly which `wl_signal_add()` call in `view_child_init()` might help narrow down the crash

**Comment by emersion** [comment]
This patch changes the wlroots API: `wlr_surface_get_root_surface` wouldn't return NULL previously, now it can.

Do we know why `subsurface->parent` is NULL? Parent surface destroyed before the subsurface?

**Comment by ifreund** [comment]
> Parent surface destroyed before the subsurface?

That's my assumption reading the code though I haven't had the chance to really dig into this with a debugger.

**Review by emersion — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
