### PR TITLE
Check if crtc is null in in cursor cleanup when output removed

### LINKED ISSUE #575: Hotplugging outputs DRM on rootston (and pointer example) causes segfault
This also happens in the cursor example.

To reproduce:
* Have two monitors plugged in
* Start rootston/pointer example
* Unplug one of the monitors -> witness segfault

It's caused by trying to set the hardware cursor in the DRM module, based on this stacktrace:

```
Core was generated by `./rootston'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f5d321c302a in wlr_drm_connector_set_cursor (output=0x55780ea1ca40, buf=0x0, stride=0, width=0, height=0, hotspot_x=0, hotspot_y=0, update_pixels=true) at ../backend/drm/drm.c:504
504             struct wlr_drm_plane *plane = crtc->cursor;
(gdb) bt
#0  0x00007f5d321c302a in wlr_drm_connector_set_cursor (output=0x55780ea1ca40, buf=0x0, stride=0, width=0, height=0, hotspot_x=0, hotspot_y=0, update_pixels=true) at ../backend/drm/drm.c:504
#1  0x00007f5d321dee6b in wlr_output_cursor_destroy (cursor=0x55780ea8b420) at ../types/wlr_output.c:720
#2  0x00007f5d321d9172 in output_cursor_destroy (output_cursor=0x55780ea822e0) at ../types/wlr_cursor.c:105
#3  0x00007f5d321da472 in handle_layout_output_destroy (listener=0x55780ea82300, data=0x55780e8ac460) at ../types/wlr_cursor.c:522
#4  0x00007f5d321defd7 in wl_signal_emit (signal=0x55780e8ac488, data=0x55780e8ac460) at /usr/include/wayland-server-core.h:388
#5  0x00007f5d321df0c0 in wlr_output_layout_output_destroy (l_output=0x55780e8ac460) at ../types/wlr_output_layout.c:49
#6  0x00007f5d321dfa80 in wlr_output_layout_remove (layout=0x55780e7f93a0, output=0x55780ea1ca40) at ../types/wlr_output_layout.c:289
#7  0x000055780c03fe25 in output_remove_notify (listener=0x55780e8ef3f8, data=0x55780ea1ca40) at ../rootston/output.c:409
#8  0x00007f5d321ca7a5 in wl_signal_emit (signal=0x55780e225528, data=0x55780ea1ca40) at /usr/include/wayland-server-core.h:388
#9  0x00007f5d321cabfb in output_remove_reemit (listener=0x55780e932f28, data=0x55780ea1ca40) at ../backend/multi/backend.c:122
#10 0x00007f5d321c11fb in wl_signal_emit (signal=0x55780e22f518, data=0x55780ea1ca40) at /usr/include/wayland-server-core.h:388
#11 0x00007f5d321c48b5 in wlr_drm_connector_cleanup (conn=0x55780ea1ca40) at ../backend/drm/drm.c:939
#12 0x00007f5d321c41df in wlr_drm_scan_connectors (drm=0x55780e22f4d0) at ../backend/drm/drm.c:812
#13 0x00007f5d321c0d8c in drm_invalidated (listener=0x55780e22f5d0, data=0x55780e225590) at ../backend/drm/backend.c:99
#14 0x00007f5d321bf30f in wl_signal_emit (signal=0x55780e240810, data=0x55780e225590) at /usr/include/wayland-server-core.h:388
#15 0x00007f5d321bf42c in udev_event (fd=6, mask=1, data=0x55780e225590) at ../backend/session/session.c:52
#16 0x00007f5d31f959b2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#17 0x00007f5d31f9414c in wl_display_run () at /usr/lib/libwayland-server.so.0
#18 0x000055780c03e482 in main (argc=1, argv=0x7ffc70ef39e8) at ../rootston/main.c:83 
```

If I had to guess we might need to do a similar check as we did in #564, but I don't know enough about DRM and hardware cursor unmapping to make more than an educated guess.

Not sure when this regression happened, as I remember this hotplugging working a while ago.

### PR DESCRIPTION
**Pull request by Timidger**
This fixes #575, but I'm not sure if this is not patching over a different problem (don't know the DRM code).

### CODE REVIEW

**Comment by VincentVanlaer** [comment]
Had the same issue two days ago. I feel the problem lies more in the location of `	wl_signal_emit(&drm->backend.events.output_remove, &conn->output);`
at the end of `wlr_drm_connector_cleanup`. I think this should happen before the connector itself is cleaned up.

**Comment by emersion** [comment]
@VincentVanlaer That won't fix the issue if the output is already in the `WLR_DRM_CONN_NEEDS_MODESET` or `WLR_DRM_CONN_DISCONNECTED` state.

I think we want that check anyway in case someone calls `wlr_output_set_cursor` on an output in the `WLR_DRM_CONN_NEEDS_MODESET` or `WLR_DRM_CONN_DISCONNECTED` state. Can you add similar checks to other functions as well?

**Comment by Timidger** [comment]
Added it to some of the other functions. If they don't make sense in some of them / we should do something different instead of return or if I missed one tell me.

**Comment by emersion** [comment]
Nice! There's just one missing test in `wlr_drm_connector_move_cursor`

**Comment by VincentVanlaer** [comment]
@emersion Fair point, makes sense.

**Comment by emersion** [comment]
Thanks!

**Pull request merged**
