### PR TITLE
session: Remove logind backend

### PR DESCRIPTION
**Pull request by kennylevinsen**
Rely on libseat instead.

See https://github.com/swaywm/wlroots/issues/2755

### CODE REVIEW

**Comment by emersion** [comment]
Any reason why this is WIP?

**Comment by kennylevinsen** [comment]
> Any reason why this is WIP?

Just to avoid premature merge while 0.13.0 was being hashed out.

**Comment by kennylevinsen** [comment]
Marking as breaking change as this removes `WLR_HAS_SYSTEMD` and `WLR_HAS_ELOGIND`.

**Review by emersion — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
