### PR TITLE
Minor output cleanup

### PR DESCRIPTION
**Pull request by emersion**
See the individual commits.

Breaking change: `wlr_output_impl.transform` has been removed.

### CODE REVIEW

**Comment by ddevault** [comment]
At some point weren't we thinking of implementing output transforms for DRM?

**Comment by ascent12** [comment]
It's really hard to make use of properly (e.g. it only works correctly on intel with certain modifiers), and most drivers don't support a lot of transforms anyway, especially not useful ones like 90 or 270.
I'm fine with removing it.

**Comment by ddevault** [comment]
Thanks!

**Comment by emersion** [comment]
>At some point weren't we thinking of implementing output transforms for DRM?

Re-posting the commit message in case you missed it:

>We could add support for hardware transforms, but:
>
> - This would require a different field (something like hardware_transform)
> - Not all combinations are possible because there often are hardware
>   limitations
> - The Wayland protocol isn't ready for this (in particular xdg-output, see [1])
>
> This belongs to a different patch series anyway.

[1]: https://patchwork.freedesktop.org/series/52324/

**Pull request merged**
