### PR TITLE
Maximize views in rootston

### LINKED ISSUE #343: Rootston window maximization
The xdg-shell currently has no hook for when a window wants the be maximized. This happens when an xdg-toplevel commits a surface state with the maximized bit set.

At this point, rootston is supposed to reposition the window and send a configure event with the new geometry.

wl-shell and xwayland have similar interfaces.

### PR DESCRIPTION
**Pull request by emersion**
Test plan: click on the maximize button of a window. Click on it again. Try to move/resize/rotate a maximized window. Test with these clients:
* xdg-shell: `gnome-dictionary`
* xwayland: `env GDK_BACKEND=x11 gnome-dictionary`
* wl-shell: https://gist.github.com/emersion/08490666de3750386c0b87d7b49d27d3 (right click to maximize)

Fixes #343

### CODE REVIEW

**Comment by emersion** [comment]
This PR is ready for review.

**Comment by SirCmpwn** [comment]
Test plan could stand to mention some good clients to test with

**Comment by emersion** [comment]
Test clients: `weston-terminal`, `gnome-dictionary` (double-click on titlebar, more difficult to test with), `env GDK_BACKEND=x11 gnome-dictionary` (that one doesn't seem to work, adding a TODO).

**Comment by emersion** [comment]
Fixed all issues, ready for review (for real this time!).

**Comment by SirCmpwn** [comment]
* xdg-shell: gnome-dictionary - **works** but there's a weird delay between double clicking the titlebar and the maximize happening
* xwayland: env GDK_BACKEND=x11 gnome-dictionary **does not work**
* wl-shell: https://gist.github.com/emersion/08490666de3750386c0b87d7b49d27d3 (right click to maximize) **works**

I also tested gnome-terminal and the delay was much more apparent - it seemed to not kick in until I dragged the cursor out of the terminal. gedit under X11 shows the same behavior as gnome-dictionary under X11.

**Comment by SirCmpwn** [comment]
All of those tests were conducted under the wl backend.

**Comment by emersion** [comment]
>xwayland: env GDK_BACKEND=x11 gnome-dictionary does not work

As discussed on IRC, this is due to #330. Don't resize rootston.

>there's a weird delay between double clicking the titlebar and the maximize happening

Just fixed that.

**Pull request merged**
