### PR TITLE
primary-selection-v1: copy from gtk-primary-selection

### PR DESCRIPTION
**Pull request by emersion**
This is a verbatim copy of gtk-primary-selection, with interfaces renamed.

I don't know of any clients implementing this yet.

- [x] Port https://github.com/swaywm/wlroots/pull/1519

Fixes https://github.com/swaywm/wlroots/issues/1367

### CODE REVIEW

**Comment by bugaevc** [comment]
Done (in wl-clipboard master already), and it seems to work!

**Comment by emersion** [comment]
Nice!

Rebased the PR.

**Comment by emersion** [comment]
Now ready for review.

**Comment by emersion** [comment]
Ping

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
