### PR TITLE
data-device: fix drag-and-drop

### PR DESCRIPTION
**Pull request by emersion**
Test plan: try out weston-dnd.

~~Depends on #1515~~
Fixes https://github.com/swaywm/wlroots/issues/1288

### CODE REVIEW

**Comment by johnchen902** [comment]
Got lots of crashes today after updating from swaywm/sway@68a28e48 and 018727b1 to swaywm/sway@4f4424f6 and 77c25c15. Do not know how to reproduce.

Do you think this pull request will fix the crashes? Should I open a separate issue?

Here are two of the crashes today:

Crash 4: [sway-19223.core.gz](https://github.com/swaywm/wlroots/files/2811735/sway-19223.core.gz)

Crash 5: [sway-valgrind-17048.log](https://github.com/swaywm/wlroots/files/2811687/sway-valgrind-17048.log) (with `i965_dri.so` suppressed)

**Comment by emersion** [comment]
Seems like it.

**Comment by emersion** [comment]
This is now ready for review.

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
