### PR TITLE
rootston: add arbitrary libinput config 'tap_enabled'

### PR DESCRIPTION
**Pull request by martinetd**
This ought to be enough to serve as an example for other compsitors to use.

I've already done the sway config as well, so not sure this is actually strictly neeeded, but I guess it can't hurt?

One last reference to #497 to properly close it in my head :)

### CODE REVIEW

**Comment by emersion** [comment]
I'd like to rename `wlr_libinput_get_device_handle(device)` to `wlr_input_device_get_libinput(device)` or something like that.

**Comment by martinetd** [comment]
If we rename this, let's do it before the sway side gets merged. I have no preference here. Others?

**Comment by SirCmpwn** [comment]
>I'd like to rename wlr_libinput_get_device_handle(device) to wlr_input_device_get_libinput(device) or something like that.

-1. We prefix function names with their subsystem, not half-prefix half-postfix.

**Comment by SirCmpwn** [comment]
>I'd like to rename wlr_libinput_get_device_handle(device) to wlr_input_device_get_libinput(device) or something like that.

This is actually backwards, what you're proposing is what's already the case and the opposite of your proposal is a good idea.

**Comment by SirCmpwn** [comment]
Sorry, I'm still misunderstanding you.

`wlr_input_device_is_libinput` is correct. `wlr_libinput_get_device_handle` is correct.

I see where you're coming from but let's not change it.

**Pull request merged**
