### PR TITLE
Amend typos

### PR DESCRIPTION
**Pull request by ammgws**

### CODE REVIEW

**Comment by ammgws** [comment]
@ammen99 there is also one in `protocol/wlr-gamma-control-unstable-v1.xml`, should I add that too or leave it be?

**Comment by ammen99** [comment]
I think it won't be a problem to add it to this PR.

**Comment by ammen99** [comment]
@ammgws Can you also send a PR for the protocols repo? https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-gamma-control-unstable-v1.xml#L113

**Comment by ammgws** [comment]
@ammen99 Done

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
