### PR TITLE
Set `DISPLAY` environment variable in XWayland

### LINKED ISSUE #200: Rootston does not the Xwayland DISPLAY in the environment
Can be fixed in either wlroots xwayland or in rootston, I don't care.

### PR DESCRIPTION
**Pull request by 4e554c4c**
Fixes #200

### CODE REVIEW

**Comment by 4e554c4c** [comment]
@martinetd Are you suggesting I move this after the fork?

**Comment by martinetd** [comment]
No, there already is code that should be setting DISPLAY in xserver_handle_ready()

I can reproduce so I definitely agree something isn't working :) But I don't think trying to add another setenv for DISPLAY is a proper solution.
The way xserver starting works is that we fork and start it, and when it feels like it it'll send a SIGUSR1 to notify us it's ready -- the variable only makes sense to be set at this point, that's why I had put the original setenv there.

I'll do some digging tonight if you'd like (in ~8 hours), but if you want to do something I'd like to understand why the current setup isn't working in the first place.
If we're fine with setting the envvar early, at least remove the old code that sets it :P

**Comment by 4e554c4c** [comment]
Yeah I see that now, thanks :)

**Comment by 4e554c4c** [comment]
After discussion on IRC, this turned out to not be an issue.

**Pull request closed without merging**
