### PR TITLE
Update IRC link

### PR DESCRIPTION
**Pull request by bl4ckb0ne**
/cc @emersion

### CODE REVIEW

**Comment by fluix-dev** [comment]
There's another reference in CONTRIBUTING.md

**Comment by bl4ckb0ne** [comment]
Superseded by https://github.com/swaywm/wlroots/pull/2938

**Comment by fluix-dev** [comment]
Looks good, but just wondering why the new PR :D

**Comment by bl4ckb0ne** [comment]
Mix up with the remote, I made this branch on the repo itself.

**Pull request closed without merging**
