### PR TITLE
backend: add 'wlr_backend_create_buffer' interface

### PR DESCRIPTION
**Pull request by zccrs**
Support create a new wlr_buffer by wlr_backend.

Closes: https://github.com/swaywm/wlroots/issues/2750

### CODE REVIEW

**Comment by emersion** [comment]
I don't think this is desirable, the backend is not a buffer factory. In the future, the backend will just be a means to display a `wlr_buffer`.

**Comment by emersion** [comment]
Relevant reading:

- https://github.com/swaywm/wlroots/issues/1352
- https://github.com/swaywm/wlroots/pull/2505

**Comment by zccrs** [comment]
> I don't think this is desirable, the backend is not a buffer factory. In the future, the backend will just be a means to display a `wlr_buffer`.

I agree, but I did not find a more suitable place to add it.

**Comment by zccrs** [comment]
I modified the commits of PR, it looks more reasonable, @emersion  please help me confirm whether it conforms to the design philosophy of wlroots

**Comment by emersion** [comment]
I'm not comfortable adding this as a public API, because the backend will not have an allocator in the long run.

**Comment by zccrs** [comment]
> I'm not comfortable adding this as a public API, because the backend will not have an allocator in the long run.

Is there any plan to provide a public API for the allocator?

**Comment by emersion** [comment]
You mean make `wlr_allocator` public? Yes. It's not public yet because I wanted the dust to settle (e.g. making sure software rendering would work fine with this API).

**Comment by zccrs** [comment]
> You mean make `wlr_allocator` public? Yes. It's not public yet because I wanted the dust to settle (e.g. making sure software rendering would work fine with this API).

Thank you, Is this work in progress ? In which version will you achieve this plans?

**Comment by zccrs** [comment]
@emersion  Where is the wlroots Roadmap for the next few years ? I want  focus for the wlroots, how do get some plans of the wlroots release.

**Comment by emersion** [comment]
I guess most of it is summed up in #1352. #1826 may also be relevant.

**Comment by emersion** [comment]
> Thank you, Is this work in progress ? In which version will you achieve this plans?

I hope these new APIs to make it in wlroots 0.14.0.

**Pull request closed without merging**
