### PR TITLE
subsurface: add map/unmap events

### PR DESCRIPTION
**Pull request by emersion**
Fixes https://github.com/swaywm/wlroots/issues/1414

### CODE REVIEW

**Comment by ddevault** [comment]
Should we avoid iterating over unmapped subsurfaces when rendering? Should we instruct compositors to check whether or not a subsurface is mapped when rendering?

**Comment by emersion** [comment]
Err, forgot that part. Hmm. It'd be better to handle all of this mess in wlroots. I'll work on a fix.

**Comment by emersion** [comment]
Fixed

**Comment by ddevault** [comment]
I don't follow how this new patch addresses my concern.

**Comment by emersion** [comment]
Oh, yeah, the fix was more about the map/unmap semantics for subsurfaces (described in the original issue).

About how compositors should handle it… Right now for popups we iterate over unmapped ones too. I'm not sure iterating over only mapped surfaces is a good idea, as surface iterators can be used for e.g. `wlr_surface_send_{enter,leave}`. I'd say the compositor should handle it, although Rootston doesn't do it now (not for subsurfaces, not for popups, not for toplevels, not for xwayland surfaces).

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
