### PR TITLE
append info about the behaviour of wlr_texture_from_pixels

### PR DESCRIPTION
**Pull request by werererer**
See #2437

### CODE REVIEW

**Comment by emersion** [comment]
I think this generally applies to all functions creating or updating a texture.

**Comment by werererer** [comment]
Didnt test that but may be true. I'll test it later

**Comment by werererer** [comment]
btw It seems that this issue didn't exist in prior versions couldn't reproduce it there

**Comment by emersion** [comment]
Yes, this behaviour has been introduced after properly cleaning up EGL contexts behind wlroots calls.

**Comment by werererer** [comment]
Is it cleanly fixable? I mean sometimes you have to introduce new surfaces inbetween wlr_render_begin() and end()

**Comment by emersion** [comment]
No, you shouldn't need to do this.

**Comment by emersion** [comment]
Superseded by https://github.com/swaywm/wlroots/pull/2486

**Pull request closed without merging**
