### PR TITLE
Another gcc false positive

### PR DESCRIPTION
**Pull request by orestisf1993**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
What gcc version are you using?

**Comment by orestisf1993** [comment]
```
$ gcc --version
gcc (GCC) 7.3.1 20180312
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by orestisf1993** [comment]
```
$ git checkout master
$ git clean -fdx .
$ export CFLAGS="-O2"
$ which gcc
/usr/bin/gcc
$ gcc --version
gcc (GCC) 7.3.1 20180312
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ meson build && ninja -C build
The Meson build system
Version: 0.45.1
Source dir: /home/orestis/Documents/programming/wlroots
Build dir: /home/orestis/Documents/programming/wlroots/build
Build type: native build
Project name: wlroots
Native C compiler: ccache cc (gcc 7.3.1 "cc (GCC) 7.3.1 20180312")
Appending CFLAGS from environment: '-O2'
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Native dependency wayland-server found: YES 1.14.0
Native dependency wayland-client found: YES 1.14.0
Native dependency wayland-egl found: YES 17.3.7
Native dependency wayland-protocols found: YES 1.13
Native dependency egl found: YES 17.3.7
Native dependency glesv2 found: YES 17.3.7
Native dependency libdrm found: YES 2.4.91
Native dependency gbm found: YES 17.3.7
Native dependency libinput found: YES 1.10.3
Native dependency xkbcommon found: YES 0.8.0
Native dependency libudev found: YES 238
Native dependency pixman-1 found: YES 0.34.0
Native dependency libcap found: YES 2.25
Native dependency libsystemd found: YES 238
Dependency libelogind found: NO
Library m found: YES
Native dependency xcb found: YES 1.13
Native dependency xcb-composite found: YES 1.13
Native dependency xcb-xfixes found: YES 1.13
Native dependency xcb-image found: YES 0.4.0
Native dependency xcb-render found: YES 1.13
Native dependency x11-xcb found: YES 1.6.5
Native dependency xcb-icccm found: YES 0.4.1
Native dependency xcb-xkb found: YES 1.13
Dependency xcb-errors found: NO
Configuring config.h using configuration
Configuring version.h using configuration
Program wayland-scanner found: YES (/usr/bin/wayland-scanner)
Program ../glgen.sh found: YES (/home/orestis/Documents/programming/wlroots/render/../glgen.sh)
Message: 
----------------
wlroots 0.0.1

      libcap: true
     systemd: true
     elogind: false
    xwayland: true
 x11_backend: true
   xcb-icccm: true
  xcb-errors: false
----------------

Dependency threads found: YES
Native dependency wayland-cursor found: YES 1.14.0
Program git found: YES (/usr/bin/git)
Program etags found: YES (/usr/bin/etags)
Program ctags found: YES (/usr/bin/ctags)
Build targets in project: 24
Found ninja-1.8.2 at /usr/bin/ninja
ninja: Entering directory `build'
[266/279] Compiling C object 'rootston/rootston@exe/desktop.c.o'.
FAILED: rootston/rootston@exe/desktop.c.o 
ccache cc  -Irootston/rootston@exe -Irootston -I../rootston -Iinclude -I../include -I/usr/include/libdrm -I/usr/include/libevdev-1.0/ -I/usr/include/libwacom-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/home/orestis/Documents/programming/wlroots/build -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -O0 -g -Wno-unused-parameter '-DWLR_SRC_DIR="/home/orestis/Documents/programming/wlroots"' -DWL_HIDE_DEPRECATED -O2 -MD -MQ 'rootston/rootston@exe/desktop.c.o' -MF 'rootston/rootston@exe/desktop.c.o.d' -o 'rootston/rootston@exe/desktop.c.o' -c ../rootston/desktop.c
../rootston/desktop.c: In function ‘desktop_surface_at’:
../rootston/desktop.c:714:18: error: ‘roots_output’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   if ((surface = layer_surface_at(roots_output,
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      &roots_output->layers[ZWLR_LAYER_SHELL_V1_LAYER_BOTTOM],
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ox, oy, sx, sy))) {
      ~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
[267/279] Generating symbol file 'wlroots@sha/libwlroots.so.0.0.0.symbols'.
ninja: build stopped: subcommand failed.
```

**Comment by emersion** [comment]
Thanks!

**Pull request merged**
