### PR TITLE
[wip] Role committed

### PR DESCRIPTION
**Pull request by acrisci**
Add a private role-committed func to wlr-surface to ensure the role commit handler always runs before all the other handlers. This simplifies the api by removing the need for a commit event on the role types.

Role call:

* [x] xdg-shell
* [x] wl-shell
* [x] wl_pointer-cursor (no committed func)
* [x] wl_data_device-icon
* [x] wl_subsurface (no committed func)
* [x] xwayland

### CODE REVIEW

**Comment by emersion** [comment]
👍

**Comment by emersion** [comment]
Ow, was that still WIP? Missed the last title change.

**Comment by acrisci** [comment]
No I think it was good, just waiting for the build to pass. I think it's flaky.

**Comment by SirCmpwn** [comment]
Hmm, I'm not sure I like this. I know you're pushing to unify the shell interface more, @acrisci, but this is an example where it might not make sense (i.e. abstracting features that exist in a subset of, but not all, shells). Implementation-wise the `role_data` abstraction is also iffy, it's not very type-safe and feels like a bit of a hack imo.

**Comment by SirCmpwn** [comment]
This should also almost certainly use a wl_listener rather than a plain function pointer. I would probably be happier about `role_data` if it wasn't passed along in parameters but rather was just expected to be taken out of the wlr_surface.

**Pull request merged**
