### PR TITLE
Remove wlr_ prefix from local symbols

### PR DESCRIPTION
**Pull request by emersion**
This removes the long list of prefixed-but-local symbols.

### CODE REVIEW

**Comment by ascent12** [comment]
The `libinput_` and `drm_` prefixes are encroaching on the "namespace" of their respective libraries. It could lead to a lot of confusion when debugging, and I've even run into a problem where I accidentally used one of our constants instead of a libdrm constant before.
They probably should be renamed to something else.

**Comment by emersion** [comment]
>They probably should be renamed to something else.

The only reasonable prefix I can think of is `backend_{drm,libinput}`. This isn't consistent with global functions names (prefixed with `wlr_{drm,libinput}`).

**Comment by SirCmpwn** [comment]
`backend_{drm,libinput}` is meh but I don't have a better suggestion

**Comment by emersion** [comment]
We could also assume the DRM module is self-contained and drop the `drm_` prefix.

**Comment by ascent12** [comment]
I'd be fine with that.

**Comment by emersion** [comment]
>We could also assume the DRM module is self-contained and drop the drm_ prefix.

Hmm, it seems it's not possible to apply the symbols file to archives. That means all symbols are global to wlroots.

**Comment by emersion** [comment]
>but would it matter? You basically want to have them as local symbols in the generated library/shared object so programs can't link against them.

It would have been cool to be able to define the same symbol in the libinput backend and in the DRM backend (e.g. `handle_event`).

Now that I think of it, maybe not, because it makes debugging more difficult (even if you generally have the name of the file defining the function).

**Comment by emersion** [comment]
This (boring) PR is ready for another review.

**Comment by agx** [comment]
Looks great!

**Pull request merged**
