### PR TITLE
seat: split into multiple files

### PR DESCRIPTION
**Pull request by emersion**
And remove a useless surface resource destroy listener.

Again, this is some preliminary work for #931.

### CODE REVIEW

**Comment by emersion** [comment]
Would you prefer a PR that splits these in different files?

It's pretty difficult to work on these files right now.

**Comment by SirCmpwn** [comment]
Sure.

**Comment by emersion** [comment]
Updated to split into multiple files.

**Comment by agx** [comment]
LGTM

**Pull request merged**
