### PR TITLE
output: don't destroy global immediately

### PR DESCRIPTION
**Pull request by emersion**
Depends on:

* https://gitlab.freedesktop.org/wayland/wayland/merge_requests/28 (merged upstream)
* https://gitlab.freedesktop.org/wayland/wayland/merge_requests/30 (merged upstream)

Build with Wayland's master branch.

Closes: https://github.com/swaywm/sway/issues/3625

### CODE REVIEW

**Comment by tbm** [comment]
What's the reason this is marked as "do not merge"?

Because it depends on a new wayland feature or because it needs more testing?

**Comment by emersion** [comment]
Blocked on a new Wayland release.

**Comment by ddevault** [comment]
Can we make a more generalized helper for delaying global destruction for any kind of global?

**Comment by emersion** [comment]
Wayland 1.18 has been released, so we'll soon be able to (finally!) land this. This PR is ready for review.

>Can we make a more generalized helper for delaying global destruction for any kind of global?

Yeah that's a good idea. Pushed a commit doing that a while ago.

**Comment by ddevault** [comment]
Thanks!

**Comment by layus** [comment]
I had I hopes for this PR to fix firefox crashes on reload. Sadly, my firefox still crashes on `swaymsg reload`. Is this related ?

**Comment by emersion** [comment]
Hard to say without a `WAYLAND_DEBUG=client` log.

**Pull request merged**
