### PR TITLE
rootston: default meta key

### PR DESCRIPTION
**Pull request by acrisci**

### CODE REVIEW

**Comment by emersion** [comment]
Sensible defaults are here:

https://github.com/swaywm/wlroots/blob/master/rootston/config.c#L300

Maybe we want to move that piece there?

**Comment by acrisci** [comment]
> Sensible defaults are here:

Those only get applied if no config file is found.

**Comment by SirCmpwn** [comment]
If you provide a config file it's your responsibility to make sure it's good.

**Comment by emersion** [comment]
On the same note, there's a `config->xwayland = true;` right after, if we don't want a default meta key we may not want to enable xwayland by default too (but enable it if no config file is specified).

**Comment by SirCmpwn** [comment]
I could go either way on that change.

**Pull request closed without merging**
