### PR TITLE
xdg-shell: fix inert xdg_surface handling

### PR DESCRIPTION
**Pull request by emersion**
Closes: https://github.com/swaywm/sway/issues/4834
Closes: https://github.com/swaywm/wlroots/issues/1890

### CODE REVIEW

**Comment by ammen99** [comment]
It is worth mentioning that this patch makes all applications that use `gtk-layer-shell` crash as soon as I try to open a popup. This happens in both Sway and Wayfire, with gtk-layer-demo, mate-panel and wf-panel. Popups of native GTK apps work.

**Comment by ammen99** [comment]
Oh, and without these patches, with mate-panel's popups, I can trigger an assertion inside wlroots (on Wayfire). So there is something fishy here.

**Comment by emersion** [comment]
Ah, indeed, I was rejecting a NULL `parent` arg in the `get_popup` handler, which layer-shell relies on. Can you try this updated version?

**Comment by ammen99** [comment]
@emersion Yes, it seems to work now.

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
