### PR TITLE
Dispatch events in virtual pointer example

### PR DESCRIPTION
**Pull request by puffnfresh**

### CODE REVIEW

**Comment by emersion** [comment]
This shouldn't matter, since the client will exit right after, so all client resources will get destroyed?

**Comment by kennylevinsen** [comment]
> This shouldn't matter, since the client will exit right after, so all client resources will get destroyed?

Maybe the intent here is to flush the display, rather than dispatching?

**Comment by puffnfresh** [comment]
@kennylevinsen yes thanks, I think you're right.

**Comment by emersion** [comment]
Oh, I see, I forgot that this is a one-off CLI demo that just sends a bunch of requests then exits. Yes, please call `wl_display_flush` instead.

**Review by emersion — APPROVED** [review]
Thanks!

**Pull request merged**
