### PR TITLE
xwayland: xsurface commit

### PR DESCRIPTION
**Pull request by acrisci**
Not strictly necessary (yet) but might be one day, and makes it like the other shells.

### CODE REVIEW

**Comment by emersion** [comment]
I'm not sure about this: given how xwayland works, will we ever need it? State isn't double-buffered in X11.

**Comment by emersion** [comment]
After all, you're right. We should have a best-effort approach even if X11 doesn't really double-buffer state.

**Comment by SirCmpwn** [comment]
Until this actually does something meaningful let's not.

**Comment by acrisci** [comment]
This actually does make things a bit easier now that I think about it. The xwayland surface is ephemeral so it means the user doesn't have to unsubscribe/resubscribe to the surface events on map and unmap.

**Comment by emersion** [comment]
>The xwayland surface is ephemeral so it means the user doesn't have to unsubscribe/resubscribe to the surface events on map and unmap.

Yes, but the compositor still needs to add and remove the view from the desktop when it's mapped and unmapped. So I don't think it adds a lot of value (apart from saving one line of code).

In the end, other shells define particular semantics for the surface commit event, but xwayland doesn't. It makes sense not to add it, at least for now.

**Comment by acrisci** [comment]
I think the ultimate solution here is for wlr-surface to have a special function for role surfaces to set that always runs before wlr-surface commit and get rid of all the role surface commit events.

**Comment by emersion** [comment]
Yeah, that makes sense since a surface can only have one role.

**Pull request closed without merging**
