### PR TITLE
render/gles2: remove duplicated format list

### PR DESCRIPTION
**Pull request by emersion**

### CODE REVIEW

**Comment by ddevault** [comment]
NACK. Incurs a greater runtime cost for trivial benefits. Not worth the code churn.

**Comment by emersion** [comment]
`get_gles2_wl_formats` is called once to initialize `wl_shm`. I did this because adding new formats is annoying.

**Comment by ddevault** [comment]
Adding a single line to a list is annoying? Hardly.

**Comment by emersion** [comment]
Causes issues when you want to make a format depend on the availability of a GL extension. Also error-prone, I added the format but it wouldn't show up in `weston-info`.

**Comment by ddevault** [comment]
Eh, fair enough then.

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
