### PR TITLE
xwm clipboard sync

### PR DESCRIPTION
**Pull request by acrisci**
Sync the Wayland clipboard selection with the xwm clipboard.

Tests:

* Copy from a Wayland window and paste into an Xwayland window.
* Copy from an Xwayland window and paste into a Wayland window.
* <s>`sleep 5 && xclip -o`, change focus to a wayland window, and modify the clipboard. xclip should not receive an updated value.</s> not in scope

### CODE REVIEW

**Comment by acrisci** [comment]
It basically works and it's ready for testing.

**Comment by emersion** [comment]
* Copying text from Chromium to Gedit: the first copy doesn't work, but subsequent copy operations work.
* Copying rich HTML text from Chromium and pasting it in LibreOffice strips the formatting (works in GNOME)
* Copying from a client, closing the client, and pasting doesn't work (works under X11, doesn't work in GNOME). I wonder if there's a workaround.
* `xclip -o -selection clipboard` doesn't work from wayland to xwayland (`target STRING not available`) when running in a focused wayland terminal (maybe not a bug?)
* `xclip -o -selection clipboard` segfaults from xwayland to xwayland, when running in a focused xwayland terminal. Same when copy-pasting between two xwayland windows.

```
#0  0x00007ffff79687e9 in wl_event_source_remove () at /usr/lib/libwayland-server.so.0
#1  0x00007ffff7b89d0c in xwm_read_data_source (fd=32, mask=4, data=0x55555616a390) at ../xwayland/selection.c:112
#2  0x00007ffff79689b2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#3  0x00007ffff796714c in wl_display_run () at /usr/lib/libwayland-server.so.0
#4  0x000055555555e96a in main (argc=1, argv=0x7fffffffe7d8) at ../rootston/main.c:73
```

**Comment by SirCmpwn** [comment]
Bump

**Comment by acrisci** [comment]
> Copying rich HTML text from Chromium and pasting it in LibreOffice strips the formatting (works in GNOME)

That's not going to work and I don't feel like supporting it. I hate that feature and I wish nobody ever thought of it.

> Copying text from Chromium to Gedit: the first copy doesn't work, but subsequent copy operations work.

I think this works now, and those other bugs.

There still might be some issues with this, but it's ready for more testing.

However, I don't feel like doing the extra "security feature" that was tacked onto this so I'll leave that up to someone else. If that's a requirement for merging, then I'll mark this as abandoned and keep this in my fork and share that with you guys when the time comes 😄 .

**Comment by SirCmpwn** [comment]
>That's not going to work and I don't feel like supporting it. I hate that feature and I wish nobody ever thought of it.

This is not an acceptable approach

>However, I don't feel like doing the extra "security feature" that was tacked onto this so I'll leave that up to someone else. If that's a requirement for merging, then I'll mark this as abandoned so someone else can take it up and keep this in my fork and share that with you guys when the time comes ￼ .

Dude

**Comment by emersion** [comment]
Can confirm that apart from rich clipboard and the security feature, everything works fine now.

**Pull request closed without merging**
