### PR TITLE
render: unconditionally read WLR_RENDERER

### PR DESCRIPTION
**Pull request by emersion**
Prior to this commit, WLR_RENDERER was only looked up when the
backend returned a DRM FD.

Make it so WLR_RENDERER is always looked up, so that running wlroots
on a system without a GPU and with WLR_RENDERER=gles2 fails as
expected instead of falling back to the Pixman renderer.

cc @bl4ckb0ne

### CODE REVIEW

**Comment by bl4ckb0ne** [comment]
Small nit: I'd prefer the drm fd check to be done in the `wlr_gles2_renderer_create_with_drm_fd` function so the renderer autocreate function just has to deal with NULL wlr_renderers.

LGTM otherwise :)

**Comment by emersion** [comment]
> Small nit: I'd prefer the drm fd check to be done in the wlr_gles2_renderer_create_with_drm_fd function so the renderer autocreate function just has to deal with NULL wlr_renderers.

I haven't gone with this approach because one code-path wants a `WLR_ERROR` log when there is no `drm_fd`, the other wants a `WLR_DEBUG` log. We shouldn't print a `WLR_ERROR` if we're going to try another renderer next.

**Comment by bl4ckb0ne** [comment]
Seems good then, merge when you're ready

**Comment by emersion** [comment]
Thanks for having a look!

**Pull request merged**
